In [1]:
import numpy as np

In [2]:
myarr = np.array([23,13,5,27,96])

In [3]:
myarr

array([23, 13,  5, 27, 96])

In [4]:
#you can assign the int type to manage space
ar1 = np.array([23,13,5,27,96], np.int32)

In [5]:
ar1

array([23, 13,  5, 27, 96])

In [6]:
#we have not made the array two dimensional hence we cant get data by mentioning axis
#lets make it 2d 
ar2 = np.array([[23,13,587,27,96,0]], np.int32)

In [7]:
ar2.shape

(1, 6)

In [8]:
ar2[0,3]

27

In [9]:
ar2.dtype

dtype('int32')

In [10]:
#changing value
ar2[0,2]= 68
ar2

array([[23, 13, 68, 27, 96,  0]])

**Conversion from other python struvture to create array**

In [11]:
listarray = np.array([[4,8,12],[3,6,9],[5,10,15]])

In [12]:
listarray[1]

array([3, 6, 9])

In [13]:
listarray.size

9

In [14]:
#this is an object, but if yiu want to do some math problems then don;t use object
np.array({2,4,6})

array({2, 4, 6}, dtype=object)

In [15]:
#range as arange to make array
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
lspace = np.linspace(0,12,6)

In [17]:
lspace

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. ])

In [18]:
emp = np.empty((2,3))
emp

array([[ 0. ,  2.4,  4.8],
       [ 7.2,  9.6, 12. ]])

In [19]:
emp_l = np.empty_like(lspace)

In [20]:
emp_l

array([ 0. ,  2.4,  4.8,  7.2,  9.6, 12. ])

In [21]:
id = np.identity(3)

In [22]:
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
id.shape

(3, 3)

In [24]:
ar = np.arange(12)

In [25]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
#it has to be a mulitipe of the number of value in the array
ar = ar.reshape(2,6)

In [28]:
ar

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
ar = ar.ravel()

In [31]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
ar.shape

(12,)

In [33]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [34]:
ar = np.array(x)

In [35]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
#adding the columns
ar.sum(axis=0)

array([12,  8,  9])

In [37]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [38]:
#transpose - row to column and vice versa
ar.T 

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [41]:
ar.ndim

2

In [42]:
ar.size

9

In [43]:
one = np.array([3,5,9,23,65,8])

In [48]:
#it shows at which index the required value is present
one.argmax()


6

In [46]:
one.argmin()


0

In [47]:
one.argsort()


array([0, 1, 5, 2, 3, 4], dtype=int64)

In [49]:
ar.argmin()

8

In [50]:
ar.argmax()

6

In [51]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [52]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [56]:
ar[2].argmax()

0

In [57]:
np.where(ar>3)

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [58]:
np.count_nonzero(ar)

8

In [59]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [60]:
import sys

In [61]:
py_ar = [[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]]

In [62]:
np_ar = np.array(py_ar)

In [64]:
sys.getsizeof(1)* len(py_ar)

84